title: Phuong Nguyen # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Enthusiast
  <br><br>
  Business Analytics and Information Systems major 
  <br><br>
  <a href="www.linkedin.com/in/phuong-nguyen3011">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
